name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '6 6 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Notice'
        run: bash ./notice.sh ${{ secrets.DTALK_TOKEN }} 